# Generated by Django 5.2.1 on 2025-05-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_book_download_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del género')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, help_text='Selecciona uno o varios géneros para este libro', to='libros.genre', verbose_name='Géneros'),
        ),
    ]
