# Generated by Django 5.2.1 on 2025-05-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0005_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Ranking promedio'),
        ),
    ]
